name: Verify docs

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  verify-docs:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.302'
      
    - name: Run verification script
      run: |
        dotnet tool restore
        dotnet fake build -t verifydocs
